export { ArrayStore, type ArrayStoreConfig } from './array-store';
export { DataStore, type DataStoreConfig } from './data-store';
export { DictStore, type DictStoreConfig } from './dict-store';
export { collectDictStoreConfigs, collectDictStoreIds, DictStoreService } from './dict-store.service';
export { normalizeDictRecord, type DictRecord } from './model/dict-record';
export { Page } from './page';
export { type DataProxy, type ReadParams } from './proxy/data-proxy';
export { HttpProxy } from './proxy/http-proxy';
export { MemoryProxy } from './proxy/memory-proxy';
export { CrudProxy } from './proxy/crud-proxy';
export { DefaultPageReader, getByPath, readPage, type PageReaderConfig } from './reader/page-reader';
export { StoreManager } from './store-manager';
